PDF_METADATA = {
    "Exercises for Trills - Practising the Piano.pdf": {"instrument": "piano", "type": "paper"},
    "The Art of Playing Fast Octaves Fluently_ Mastering the Technique.pdf": {"instrument": "piano", "type": "paper"},
    "Trill Exercises_ Piano Tips, Techniques & Examples.pdf": {"instrument": "piano", "type": "paper"},
    "Piano Technique by Paul White.pdf": {"instrument": "piano", "type": "paper"},
    "Securing a Fast Passage - Practising the Piano.pdf": {"instrument": "piano", "type": "paper"},
    "Sumiko Mikimoto's piano method.pdf": {"instrument": "piano", "type": "paper"},
    "Pedagogy of Piano Pedaling.pdf": {"instrument": "piano", "type": "paper"},
    "Jabusch20etal2009PianistsMotorSkillFollowUp.pdf": {"instrument": "piano", "type": "paper"},
    "Exploring_pedagogical_strategies_for_piano_sight-r.pdf": {"instrument": "piano", "type": "paper"},
    "The “Artistic Image” Concept Applied to a Fugue at the Early Stage of Piano Practice_ An Observational Study.pdf": {"instrument": "piano", "type": "paper"},
    "Piano_Performance_Techniques_and_Musical_Expressiv.pdf": {"instrument": "piano", "type": "paper"},
    "Expressivity and Musical Performance_ Practice Strategies for Pianists.pdf": {"instrument": "piano", "type": "paper"},
    "Expressive_production_of_piano_timbre_To.pdf": {"instrument": "piano", "type": "paper"},
    "11_Basic_Practice_Methods_in_University_General_Pi.pdf": {"instrument": "piano", "type": "paper"},
    "An Analysis of Effective Practice Strategies for the Performing Undergraduate University-Level Pianist.pdf": {"instrument": "piano", "type": "paper"},
    "Managing Arpeggios - Practising the Piano.pdf": {"instrument": "piano", "type": "paper"},
    "Personal_Account_on_the_Development_of_W.pdf": {"instrument": "piano", "type": "paper"},
    "Methodological_Principles_of_Piano_Technique_in_th.pdf": {"instrument": "piano", "type": "paper"},
    "Goebl2017-SpringerHandbook-PianoMovementTouch-postprint.pdf": {"instrument": "piano", "type": "paper"},
    "Pang.S.E.2025.IntersectionsPianoVariationsandPracticeKnow-HowasTeachingStrategiesforPianoTechniqueDevelopment.PosterPresentationThe14thMTNACollegiateChapterSymposiumNorm.pdf": {"instrument": "piano", "type": "paper"},
    "Continuing Abby Whiteside's Legacy_ The Research of Pianist Sophia Rosoff's Pedagogical Approach.pdf": {"instrument": "piano", "type": "paper"},
    "Fix It_ Teaching Tips for Playing Even Scales on the Piano - Yamaha Music.pdf": {"instrument": "piano", "type": "paper"},
    "Piano_sight-reading_teaching_and_music_education_A.pdf": {"instrument": "piano", "type": "paper"},
    "Improving Your Scales_ Feature Article for Piano Professional Magazine.pdf": {"instrument": "piano", "type": "paper"},
    "Effects of Practice Strategies, Metronome Use, Meter, Hand, and Musical Function on Dual-Staved Piano Performance Accuracy and Practice Time Usage of Undergraduate.pdf": {"instrument": "piano", "type": "paper"},
    "Suzuki_Mitchell_2021_researchgate.pdf": {"instrument": "piano", "type": "paper"},
}
